Setup help
twistedstream/lets-procrastinate pull request #1
Opened 2024-03-21 20:24 UTC by dchahla

-Added screenshot of service account email 
-Added sample env
-Created Prerequisites

2024-03-22 19:37 UTC, twistedstream requested changes
@dchahla, I love most of the suggested changes. The one thing I'm pushing back on a bit is the more significant structural changes to the README itself. See my file-level comment there to understand my thinking. Also, please see the request to remove the JS code formatting changes that I think automatically got included by your IDE.

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +CSRF_SECRET=FJW12WV1SGxqQmoremF2ejlaTXQzT2342343QySlp1TTRlcnJh234bkJRcEZZa0Z
Make this a more human-readable fake secret like `my-csrf-secret`

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +GOOGLE_AUTH_CLIENT_EMAIL=spreadsheets@api-project-010101.iam.gserviceaccount.com
This looks generic, but making sure it's not a real service account email

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +GOOGLE_SPREADSHEET_ID=1qx1niFaW62YPXNQGcyMMvR2P_srUyzCZ4mdyPX3Udrk
Just making sure this isn't a real Google Spreadsheet ID. It might be better to use something like `my-google-spreadsheet-id`

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +COOKIE_SECRET=FJWWV1jlaTX234234234p1T2342323424TRlcnJhbkJRcE234234234ZZ
Make this a more human-readable fake secret like `my-cookie-secret`

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +PORT=3000
Per the [docs](https://github.com/twistedstream/lets-procrastinate/blob/0_only-passwords/CONFIG.md#port) this should be `443` since most likely we're providing an example for local development

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +RP_ID=letsprocrastinate.dev
`RP_ID` doesn't get introduced [until chapter 1](https://github.com/twistedstream/lets-procrastinate/blob/1_offering-passkeys/CONFIG.md#rp_id), so it won't make sense to show it here. What should happen is we add it to your `.sample.env` file in that branch.

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +RP_NAME=`LetsProcrastinate`
Same comment for `RP_NAME` as I made for `RP_ID`

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
> +BASE_URL=https://letsprocrastinate.dev
Same comment for `BASE_URL` as I made for `RP_NAME` and `RP_ID`

2024-03-22 19:37 UTC, twistedstream commented on CONFIG.md
> +1. Create a Service Account credential in the Google Cloud Console (https://console.cloud.google.com/)
```suggestion
1. Create a Service Account credential in the [Google Cloud Console](https://console.cloud.google.com/)
```

2024-03-22 19:37 UTC, twistedstream commented on CONFIG.md
> +   cat api-project-1010101.json | ./node_modules/json/lib/json.js  private_key | base64
```suggestion
   cat /path/to/google-key-file.json | ./node_modules/json/lib/json.js private_key | base64
```

I like that [you added](https://github.com/dchahla/docker-procrastinate/blob/0_only-passwords/package.json#L50) the `json` package to `devDependencies` in the `package.json` file. Let's just suggest that command instead of both. My preference is to keep the origin `/path/to/google-key-file.json` as shown above.

2024-03-22 19:37 UTC, twistedstream commented on README.md
> +The following instructions will assume you're running the server locally. See the [Docker](#docker) section for production environments.
```suggestion
The following instructions will assume you're running the server locally. See the [Docker](#docker) section for information on how to run it anywhere.
```

Chances are people won't be running this sample in a "production" environment. But they may want to fire it up in Docker somewhere so they don't have to install all of the Node tooling.

2024-03-22 19:37 UTC, twistedstream commented on routes/index.js
It looks like your JS formatting rules are different than mine (eg. yours use `'` instead of `"`). I'm not seeing any functional changes to this file, so perhaps exclude it from your PR. Alternatively, you could set up Prettier in VS Code. Perhaps we need a prettier config file (something more than the [.prettierignore](https://github.com/twistedstream/lets-procrastinate/blob/1_offering-passkeys/.prettierignore) file to drive it consistently.

2024-03-22 19:37 UTC, twistedstream commented on scripts/utils.js
(Same comment applies for this file as `routes/index.js`)

2024-03-22 19:37 UTC, twistedstream commented on server.js
(Same comment applies for this file as `routes/index.js`)

2024-03-22 19:37 UTC, twistedstream commented on media/share-spreadsheet_900.png
Rename this file to have the same naming convention as the other files in `media/`.  
So maybe: `chapter-1-share-spreadsheet.png`

2024-03-22 19:37 UTC, twistedstream commented on media/share-spreadsheet_900.png
Edit this image so actual identifiers and any PII you don't want shared is blurred or blocked out. Here's an example:

![](https://github.com/twistedstream/google-sheets-table/blob/main/media/share-access.png?raw=true)

2024-03-22 19:37 UTC, twistedstream commented on README.md
> + ![Google Spreadsheet share](./media/share-spreadsheet_900.png)
Using the corrected image file name from my other comment

2024-03-22 19:37 UTC, twistedstream commented on .sample.env
Having a `.sample.env` file is a great idea!

2024-03-22 19:37 UTC, twistedstream commented on README.md
> -### Environment
Let's keep the `### Environment` section

2024-03-22 19:37 UTC, twistedstream commented on README.md
> -### Database
Let's keep the `### Database` section

2024-03-22 19:37 UTC, twistedstream commented on README.md
> -Export the environment variables specified in [CONFIG](./CONFIG.md). For local development, you can use a `.env` file.
Let's keep this description, but I like the idea of incorporating the use of the `.sample.env` file. So maybe modify the line to something like:

```
Export the environment variables specified in [CONFIG](./CONFIG.md). For local development, you can use a `.env` file, which can easily be created by copying the [.sample.env](./.sample.env) file to `.env`.
```

2024-03-22 19:37 UTC, twistedstream commented on README.md
While I understand why the purpose of the restructuring of the README, I'd like to maintain the original organization as it was since its designed to support both the local developer (who would need to install Node, etc) and the operator who just wants to try the sample using Docker. I've made a few comments in this file where I liked the specific change, but the other changes I think I'd like to hold off doing.

2024-03-22 19:58 UTC, dchahla commented
Done!

2024-03-24 22:25 UTC, twistedstream commented
These changes have been merged into the `0_only-passwords` branch through a squashed merge with a few extra changes.

2024-03-24 22:25 UTC, closed without merging